version: '3.7'

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-container
    image: localhost/backend-image
    ports:
      - 8000:8000
      - 10001:10001
    volumes:
      - ./backend:/backend-code
    # command: "sh ./docker-backend-entry.sh"
    # restart: always
    env_file:
      - backend/.env
    # links:
    #   - redis
    depends_on:
      - db
    environment:
      TZ: "Asia/Taipei"

  
  db:
    container_name: db-container
    image: postgres:12-alpine3.17
    restart: always
    environment:
      POSTGRES_USER: develop
      POSTGRES_DB: zipproject
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /podman-pgdata
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data


